# Porta da API
server.port=8080

# URL do banco (cria a base automaticamente se não existir)
spring.datasource.url=jdbc:mysql://localhost:3306/all_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678

# Driver JDBC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate (Dialeto removido para detecção automática)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true